---

- name: Install nginx
  hosts: localhost
  tasks:
    - name: Install nginx
      apt: 
      name: nginx
      state: present
     
    - name: Start Service
      apt: 
      name: nginx
      service: restart
