---

- name: Install nginx
  hosts: localhost
  tasks:
    - name: Install nginx
      apt: 
      name: nginx
      state: present
    - name: copying nginx config
      copy:
        src: /home/ubuntu/default
        dest: /etc/nginx/sites-available/default    
    - name: Start Service
      apt: 
      name: nginx
      service: restart
